// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string):Promise<boolean>;

export function FetchWeather():Promise<main.WeatherData>;

export function GetCity():Promise<string>;

export function GetSystemStats():Promise<main.SystemStats>;

export function GetTodos():Promise<Array<main.TodoItem>>;

export function Quit():Promise<void>;

export function RemoveTodo(arg1:number):Promise<boolean>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetCity(arg1:string):Promise<void>;

export function ToggleTodo(arg1:number):Promise<boolean>;
