// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function FetchWeather() {
  return window['go']['main']['App']['FetchWeather']();
}

export function GetCity() {
  return window['go']['main']['App']['GetCity']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveTodo(arg1) {
  return window['go']['main']['App']['RemoveTodo'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetCity(arg1) {
  return window['go']['main']['App']['SetCity'](arg1);
}

export function ToggleTodo(arg1) {
  return window['go']['main']['App']['ToggleTodo'](arg1);
}
